### ISSUE TITLE
Dashboard 

### ISSUE THREAD

**Issue by CokkocZateki** [xaronnn/ember-modules#1]
Hi

Would be great to have a dashboard after signing into Ember. Would work great when it came to linking a discord account.the date a player donated to a server and when it will expire. A place to see where support tickets/applications will show open/closed reports. Seeing all liked and commented messages from Better Profile. Could also add what position on the leaderboard a player is on and have some in game stats for that player

**Comment by xaronnn** [comment]
Thanks for the your idea.

**Comment by Noobforlife** [comment]
Hey. A better Dashboard like this would be awesome
https://blog.krasin.space/rustdash-admin-player-dashboard-for-your-rust-server/

**Comment by xaronnn** [comment]
It's really big request. Really takes my time to do this. However, if i got front-payment for this, I can start doing it.
