### ISSUE TITLE
Better tickets broke after update

### ISSUE THREAD

**Issue by Theedgeclan2** [xaronnn/ember-modules#11]
So now in discord when someone do a ticket it shows NaN #0 was opened and the link to the ticket is website.com/support/view/0 always even I get redirected after I put in a ticket to that url

**Comment by Theedgeclan2** [comment]
LATEST version 2.5.2

**Comment by Theedgeclan2** [comment]
Previous ember version: 2.5.1 
Current ember version:  2.5.2
Current module version: 1.1.4 
Current php version: php73
development mode is enabled? no

**Comment by xaronnn** [comment]
Fixed in the last update.
