### ISSUE TITLE
Profile STATS not showing.

### ISSUE THREAD

**Issue by xmxv** [xaronnn/ember-modules#12]
After installing and reinstalling the latest version of Better Profile. The Profile STATS do not show. Everything else works great, the Leaderboard is fine, everything is defined and even had some help from Glasiore in figuring out that it wasn't caused by my end. 

Link for reference : https://skitzy.net

**Comment by xaronnn** [comment]
I looked your website and i see "bad db selected". Please can u re-configure better profile? I just updated my ember and every better module is working.

**Comment by xmxv** [comment]
Can you provide example? I have set it up again. Doesn't seem to be functional.
