### ISSUE TITLE
Better Discord

### ISSUE THREAD

**Issue by Noobforlife** [xaronnn/ember-modules#3]
Hi.

Firstly thank you for the amazing products and for supporting Ember.

My biggest wishlist item.

A Better Discord. Allowing owners the chance to send important forum posts to Discord (embedded)

Allowing a player who purchases a VIP package to see how long until their package ends. Or a little reminder of when the package will end 

Better Tickets. Whenever a ticket is made it could send a Embedded message to Discord to notify the owners they have a new ticket. When a admin replies it can send a message to a link member that they have recieved a reply to their message.

Ember on Discord has such a great potential that its the smallest puzzle missing in all of this

**Comment by xaronnn** [comment]
Thanks for the your idea. I'll make Better Discord notifications for Better module series and default ember features like forums.
