### ISSUE TITLE
Better ticketz

### ISSUE THREAD

**Issue by Theedgeclan2** [xaronnn/ember-modules#6]
Ajax error 500 lot of people keep saying they can’t put in a ticket

**Comment by xaronnn** [comment]
> Ajax error 500 lot of people keep saying they can’t put in a ticket

Can you give me more details for this problem?

**Comment by Theedgeclan2** [comment]
People still have the same problem on chrome  but 2 people use chrome 1 gets ajax and other works fine no proxy or vpn

**Comment by xaronnn** [comment]
> People still have the same problem on chrome but 2 people use chrome 1 gets ajax and other works fine no proxy or vpn

I'll make custom build for you, can u pm to our dev team on Discord?
Miu#3686

**Comment by Theedgeclan2** [comment]
I pm you but i don’t know 🤷‍♀️ what’s going on at this point I’m lost.
