### ISSUE TITLE
ERROR CODE XUNDEFINED

### ISSUE THREAD

**Issue by Theedgeclan2** [xaronnn/ember-modules#8]
cant use mobile for this is all errors 905 for better tickets and profile ERROR CODE XUNDEFINED

**Comment by xaronnn** [comment]
On mobile, VPN/Proxy is enabled?
On mobile, which browser u r using?

**Comment by Theedgeclan2** [comment]
Sefari and no vpn or proxy

**Comment by xaronnn** [comment]
> Sefari and no vpn or proxy

Some libraries, don't working on some browsers. Can u try again on modern browser like chrome, opera?
