### ISSUE TITLE
Better Profile Stats 

### ISSUE THREAD

**Issue by Noobforlife** [xaronnn/ember-modules#9]
Hello

There appears to be a bug whereby player stats seem to disappear if you open a players profile it will appear the first time

![image](https://user-images.githubusercontent.com/15904515/108622858-da579f00-743b-11eb-9cfc-83c570add1e6.png)

If you select a different server the stats disappear as shown below

![image](https://user-images.githubusercontent.com/15904515/108622872-f0655f80-743b-11eb-8775-77ab81723af9.png)

**Comment by xaronnn** [comment]
> Hello
> 
> There appears to be a bug whereby player stats seem to disappear if you open a players profile it will appear the first time
> 
> ![image](https://user-images.githubusercontent.com/15904515/108622858-da579f00-743b-11eb-9cfc-83c570add1e6.png)
> 
> If you select a different server the stats disappear as shown below
> 
> ![image](https://user-images.githubusercontent.com/15904515/108622872-f0655f80-743b-11eb-8775-77ab81723af9.png)

Hi, can you tell me your website link? I need to look.

**Comment by Noobforlife** [comment]
> > Hello
> > There appears to be a bug whereby player stats seem to disappear if you open a players profile it will appear the first time
> > ![image](https://user-images.githubusercontent.com/15904515/108622858-da579f00-743b-11eb-9cfc-83c570add1e6.png)
> > If you select a different server the stats disappear as shown below
> > ![image](https://user-images.githubusercontent.com/15904515/108622872-f0655f80-743b-11eb-8775-77ab81723af9.png)
> 
> Hi, can you tell me your website link? I need to look.

sure its https://meatballgamerz.com
